# Generated by Django 5.0.6 on 2024-06-11 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='rating',
            new_name='ratings',
        ),
        migrations.RenameField(
            model_name='customuserrating',
            old_name='rating',
            new_name='ratings',
        ),
    ]
