# Generated by Django 5.0.6 on 2024-06-11 13:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_rating_customuser_ratings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuserrating',
            name='ratings',
            field=models.FloatField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
