# Generated by Django 5.0.6 on 2024-06-11 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_customuserrating_ratings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuserrating',
            old_name='ratings',
            new_name='rating',
        ),
    ]
